default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  timeout: 3306

development:
  database: booksbug_development
  <<: *default

test:
  database: booksbug_test
  <<: *default

production:
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  <<: *default